### ISSUE TITLE
Hello what is [Notary] server mean?

### ISSUE THREAD

**Issue by fangjiataizi** [tlsnotary/pagesigner-browserless#2]
I use the default Notary server to run , but I get the following error:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.158.251.14', port=10011): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107adfc50>: Failed to establish a new connection: [Errno 60] Operation timed out',)

How to solve it and how to setup an Notary server ? Thanks

**Comment by themighty1** [comment]
@fangjiataizi  , sorry for taking this long to respond. Somehow your issue flew under the radar, Please try the updated version.

**Comment by fangjiataizi** [comment]
您好，邮件已经收到！谢谢！
