### ISSUE TITLE
To-the-second?

### ISSUE THREAD

**Issue by garyrob** [tlsnotary/pagesigner-browserless#3]
Hello,

I was able to successfully run it on MacOS! Thank you!! On my setup, the timestamp is about a minute later than the request was submitted.

In the original issue, you mentioned: "It would be possible to achieve a to-the-second timestamp if the website supports TLS resumption (which most websites do). The client and the notary would exchange all the 2PC data and perform 2PC computations in advance. The client would then resume a TLS session and immediately send the prepared request to the host.
(you can check with https://www.ssllabs.com/ssltest/index.html if resumption is supported by the host )"

Is that something that would be hard to do? If not, it seems like it would add usefulness!

**Comment by themighty1** [comment]
Hey, glad it worked for you.
There is are no immediate plans to add session resumption. Adding it would require a new 2PC circuit.

**Comment by garyrob** [comment]
OK, given that it requires significant new work, it makes sense to wait to see a significant demand for it before considering adding it. Thanks for the feedback.
